
import React, { useState, useEffect } from 'react';
import { Database, FileText, CheckCircle2, AlertTriangle, ShieldCheck } from 'lucide-react';

const INITIAL_SKILLS = [
  { id: 'S-0x41', name: 'Recursive_Latex_Synthesis', status: 'PROMOTED', ratio: '4.2x', date: '2026.04.16' },
  { id: 'S-0x92', name: 'Dialectic_User_Modeling_B', status: 'PROMOTED', ratio: '2.1x', date: '2026.04.17' },
  { id: 'S-0xFC', name: 'Context_Shear_Optimization', status: 'EVALUATING', ratio: '8.9x', date: '2026.04.17' },
  { id: 'S-0x11', name: 'Adversarial_Rollout_V3', status: 'GATED', ratio: '1.0x', date: '2026.04.15' },
];

export const SkillMatrix = () => {
  const [skills, setSkills] = useState(INITIAL_SKILLS);

  // Poll local storage to pick up skills generated by the TrainingPod
  useEffect(() => {
    const handleStorage = () => {
      const saved = JSON.parse(localStorage.getItem('hermes_skills') || '[]');
      if (saved.length > 0) {
        setSkills([...saved, ...INITIAL_SKILLS]);
      }
    };
    handleStorage();
    window.addEventListener('storage', handleStorage);
    const interval = setInterval(handleStorage, 2000); // Also poll just in case
    return () => {
      window.removeEventListener('storage', handleStorage);
      clearInterval(interval);
    }
  }, []);

  const clearSkills = () => {
    localStorage.removeItem('hermes_skills');
    setSkills(INITIAL_SKILLS);
  };
  return (
    <div className="p-8 bg-[#121212] border border-[#2a2a24] rounded-sm h-full overflow-hidden flex flex-col relative">
      <div className="flex justify-between items-center mb-8">
        <h3 className="text-[10px] font-mono font-bold uppercase tracking-[0.3em] text-[#8c8c85] flex items-center gap-3">
            Skill_Repo [FTS5]
        </h3>
        <span className="text-[9px] font-mono text-[#b49e6f]/50 uppercase tracking-tighter">
            Persistent: substrate.db
        </span>
      </div>

      <div className="flex-1 space-y-4 overflow-y-auto pr-2 scrollbar-none">
        {skills.map((skill) => (
          <div key={skill.id} className="group p-4 border border-[#2a2a24] bg-[#0c0c0c] rounded-sm hover:border-[#b49e6f]/30 transition-colors cursor-pointer relative overflow-hidden">
            <div className="flex justify-between items-start mb-3">
              <div className="flex items-center gap-3">
                <span className="text-[10px] font-mono text-[#b49e6f]">{skill.id}</span>
              </div>
              <StatusBadge status={skill.status as any} />
            </div>
            
            <h4 className="text-sm font-serif italic text-[#e6e6e3] group-hover:text-[#b49e6f] transition-colors leading-tight">
              {skill.name}
            </h4>
            
            <div className="mt-4 flex items-center justify-between border-t border-[#2a2a24] pt-3">
              <div className="flex flex-col gap-0.5">
                <span className="text-[8px] uppercase font-mono tracking-widest text-[#8c8c85]">Compression</span>
                <span className="text-[10px] font-mono text-[#b49e6f]">{skill.ratio}</span>
              </div>
              <div className="flex flex-col items-end gap-0.5">
                <span className="text-[8px] uppercase font-mono tracking-widest text-[#8c8c85]">Indexed</span>
                <span className="text-[10px] font-mono text-[#8c8c85]">{skill.date}</span>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-8 flex gap-3">
        <button className="flex-1 bg-[#121212] hover:bg-[#1a1a1a] border border-[#2a2a24] text-[#b49e6f] text-[10px] font-mono uppercase tracking-widest py-3 rounded-sm transition-all">
          Commit_Delta
        </button>
        <button onClick={clearSkills} className="flex-1 bg-transparent hover:bg-red-950/10 border border-red-900/20 text-red-900/60 text-[10px] font-mono uppercase tracking-widest py-3 rounded-sm transition-all text-center">
          Prune Generated
        </button>
      </div>
    </div>
  );
};

const StatusBadge = ({ status }: { status: 'PROMOTED' | 'EVALUATING' | 'GATED' }) => {
  const styles = {
    PROMOTED: 'text-[#b49e6f] border-[#b49e6f]/30 bg-[#b49e6f]/5',
    EVALUATING: 'text-[#e6e6e3] border-[#2a2a24] bg-[#121212]',
    GATED: 'text-red-900 border-red-900/20 bg-red-950/5'
  };

  const icons = {
    PROMOTED: <CheckCircle2 className="w-2.5 h-2.5" />,
    EVALUATING: <span className="w-2.5 h-2.5 border-b border-[#b49e6f] rounded-full animate-spin" />,
    GATED: <AlertTriangle className="w-2.5 h-2.5" />
  };

  return (
    <div className={`flex items-center gap-1.5 px-2 py-0.5 border text-[8px] font-mono uppercase tracking-widest ${styles[status]}`}>
      {icons[status]}
      {status}
    </div>
  );
};
